default:
  tags:
    - shell-runner

stages:
  - build
  - deploy

deploy:
  name: Build/deploy images and/or debian packages
  stage: deploy
  script:
    - curl 'https://gitlab.mikenopa.network/public-data/docker/-/raw/production/bin/drun-installer?inline=false' | bash
    - ./drun mikdim-script
  artifacts:
    paths:
      - "out-deb/*"
